#
# UFC-crypt: ultra fast crypt(3) implementation
# Copyright (C) 1991, 1992, Michael Glad, email: glad@daimi.aau.dk
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public
# License along with this library; if not, write to the Free
# Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# @(#)Makefile	2.12 1/23/92
#

#
# Select one of the following modules:
#
CRYPT = crypt.o

# portable C version:  crypt.o
# SUN3 models:         crypt.sun3.o
# HP series 300/400:   crypt.s300.o
# SUN SPARC systems:   crypt.sparc.o

#
# Which compiler & optimization flags to use
#
CC = gcc
OFLAGS = -O -DSYSV -DUSG

# If your system does not have a ranlib(1) command, you 
# will have to comment out the ranlib command in the 
# 'libufc.a' clauses

#
# End-of-configuration
#

CFLAGS   = $(OFLAGS) $(FL)
CRYPTOBJ = crypt_util.o $(CRYPT)

#
# Sample programs for debugging/testing/benchmarking
#

# Simple test for correct operation
ufc: ufc.c libufc.a
	$(CC) $(CFLAGS) ufc.c libufc.a -o ufc

all: ufc speedf speedc cert
tests: cert ufc speedc speedf
	./cert < ./cert.data
	./ufc 1
	./speedc
	./speedf

# Benchmark UFC fcrypt the crypt(3) in libc.a
speedf: libufc.a speeds.c
	$(CC) $(CFLAGS) -DFCRYPT speeds.c libufc.a -o speedf
speedc: libufc.a speeds.c
	$(CC) $(CFLAGS)          speeds.c          -o speedc

# DES validation suite
cert: libufc.a cert.c
	$(CC) $(CFLAGS) cert.c libufc.a -o cert

#

libufc.a: $(CRYPTOBJ)
	ar r libufc.a $(CRYPTOBJ)
	ranlib libufc.a

crypt_util.o: crypt_util.c ufc-crypt.h

#
# Crypt functions
#

# Semiportable
crypt.o: crypt.c ufc-crypt.h

# Sun3 
crypt.sun3.o: crypt.sun3.S
	./S2o crypt.sun3.S crypt.sun3.o

# HP 9000 series 300
crypt.s300.o: crypt.s300.S
	./S2o crypt.s300.S crypt.s300.o

# SUN SPARC architecture
crypt.sparc.o: crypt.sparc.S
	./S2o crypt.sparc.S crypt.sparc.o

clean:
	/bin/rm -f *.o core *~ ufc libufc.a speedf speedc tmp.s mon.out cert \
          a.out Part*

kit:
	makekit COPYING README Makefile S2o crypt.c speeds.c *.S crypt_util.c \
		ufc.c cert.c cert.data patchlevel.h ufc-crypt.h
